// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function Config():Promise<wails.Response_github_com_yukihito_jokyu_DB_checker_internal_handler_wails_ConfigData_>;

export function Status():Promise<wails.Response_github_com_yukihito_jokyu_DB_checker_internal_handler_wails_StatusData_>;
