// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateConnectionProfile(arg1) {
  return window['go']['wails']['AppHandler']['ActivateConnectionProfile'](arg1);
}

export function CheckProfiles() {
  return window['go']['wails']['AppHandler']['CheckProfiles']();
}

export function DeleteConnectionProfile(arg1) {
  return window['go']['wails']['AppHandler']['DeleteConnectionProfile'](arg1);
}

export function GetConfig() {
  return window['go']['wails']['AppHandler']['GetConfig']();
}

export function GetStatus() {
  return window['go']['wails']['AppHandler']['GetStatus']();
}

export function ListConnectionProfiles() {
  return window['go']['wails']['AppHandler']['ListConnectionProfiles']();
}

export function SaveConnectionProfile(arg1) {
  return window['go']['wails']['AppHandler']['SaveConnectionProfile'](arg1);
}
