// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CheckProfiles():Promise<wails.Response_github_com_yukihito_jokyu_DB_checker_internal_handler_wails_ProfileCheckResponse_>;

export function GetConfig():Promise<wails.Response_github_com_yukihito_jokyu_DB_checker_internal_handler_wails_ConfigResponse_>;

export function GetStatus():Promise<wails.Response_github_com_yukihito_jokyu_DB_checker_internal_handler_wails_StatusResponse_>;
